name: Update Profile Summary Cards

# Triggers the workflow every 24 hours and allows manual run
on:
  schedule:
    # Runs daily at 00:00 UTC (adjust the cron expression if you want a different time)
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    name: Generate GitHub Profile Summary Cards
    
    # Required to allow the Action to commit files back to the repository
    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Summary Cards
        # This is the official action for the cards you linked
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          # Use the secret you created in Step 2.
          # The GITHUB_TOKEN is a required env var for this specific Action.
          GITHUB_TOKEN: ${{ secrets.GH_PAT_FOR_CARDS }}
          
      - name: Commit and Push Changes
        # This action automatically commits the newly generated card files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: Update GitHub Profile Summary Cards'
          # This should point to the files the card action generates
          file_pattern: 'profile-summary-card-output/*.svg'
